#!/bin/sh

# Copyright © 2019-2021 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

if [ $# -eq 0 ]
then
    set -- "$SHELL"
fi

basefs=''
for dir in /bin /lib /lib64 /usr /etc/alternatives
do
    if [ -d "$dir" ]
    then
        basefs="$basefs --ro-bind $dir $dir"
    fi
done

passwd=$(getent passwd nobody)
IFS=: read _ _ uid gid _ <<EOF
$passwd
EOF
PATH=$(getconf PATH)
exec env -i PATH="$PATH" TERM="$TERM" HISTFILE=/dev/null \
    bwrap \
    $basefs \
    --bind . /home \
    --setenv HOME /home \
    --proc /proc \
    --dev /dev \
    --uid $uid \
    --gid $gid \
    --unshare-user-try \
    --unshare-ipc \
    --unshare-pid \
    --unshare-uts \
    --unshare-cgroup-try \
    --hostname linux \
    "$@"

# vim:ts=4 sts=4 sw=4 et
