#!/bin/sh

# Copyright © 2019 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

if [ $# -eq 0 ]
then
    set -- "$SHELL"
fi

PATH=$(getconf PATH)
exec env -i PATH="$PATH" TERM="$TERM" HISTFILE=/dev/null \
    bwrap \
    --ro-bind /bin /bin \
    --ro-bind /lib /lib \
    --ro-bind /usr /usr \
    --bind . /home \
    --setenv HOME /home \
    --proc /proc \
    --dev /dev \
    --unshare-user-try \
    --unshare-ipc \
    --unshare-pid \
    --unshare-uts \
    --unshare-cgroup-try \
    --hostname linux \
    "$@"

# vim:ts=4 sts=4 sw=4 et
